-- 코드를 작성해주세요
WITH GEN1 AS (
    SELECT  
        ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
), GEN2 AS (
    SELECT G2.ID
    FROM ECOLI_DATA G2
    JOIN GEN1 G1 ON G2.PARENT_ID=G1.ID
), GEN3 AS (
    SELECT G3.ID
    FROM ECOLI_DATA G3
    JOIN GEN2 G2 ON G3.PARENT_ID=G2.ID
)

SELECT *
FROM GEN3
ORDER BY ID

# SELECT *
# FROM ECOLI_DATA