-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT 
        D.ID,
        D.PARENT_ID,
        GENERATION + 1
    FROM ECOLI_DATA D
    INNER JOIN GEN ON GEN.ID = D.PARENT_ID
)

SELECT COUNT(GEN.ID) AS COUNT,
    GEN.GENERATION
FROM GEN
LEFT JOIN GEN GEN2 ON GEN.ID = GEN2.PARENT_ID
WHERE GEN2.ID IS NULL
GROUP BY GEN.GENERATION
