WITH BASE AS (
SELECT
    HE.EMP_NO,
    HE.EMP_NAME,
    CASE 
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    HE.SAL

FROM HR_EMPLOYEES HE
LEFT JOIN HR_GRADE HG ON HE.EMP_NO=HG.EMP_NO
GROUP BY HE.EMP_NO
)
SELECT 
    EMP_NO,
    EMP_NAME,
    GRADE,
    CASE GRADE
        WHEN 'S' THEN SAL * 0.2
        WHEN 'A' THEN SAL * 0.15
        WHEN 'B' THEN SAL * 0.1
        ELSE 0
    END AS BONUS
FROM BASE