-- 코드를 작성해주세요
SELECT ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT 1
    FROM SKILLCODES S
    WHERE (D.SKILL_CODE & S.CODE) != 0 
    AND (S.NAME = 'Python' OR S.NAME = 'C#')
)
ORDER BY ID